# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160315_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDocumentUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('doc_title', models.CharField(max_length=64)),
            ],
        ),
    ]
