# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_downloaddocumentuserrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddocumentuserrequest',
            name='doc_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
