# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 08:27
from __future__ import unicode_literals

from django.db import migrations


def create_test_people(apps, schema_editor):
    People = apps.get_model("company", "People")
    Team = apps.get_model("company", "Team")
    Job = apps.get_model("company", "Job")

    Job(name='Test Job Title', description='Test Job Description').save()
    Team(name='Board Members', description='Test Team Description').save()
    Team(name='Management Team', description='Test Team Description').save()

    for i in range(8):
        People(first_name='Jo', last_name='Blogs', phone='0181 811 8181', email='jo.blocgs@densitron.com', description='People Test Description', team_id=1, job_id=1).save()
    for i in range(8):
        People(first_name='Jo', last_name='Blogs', phone='0181 811 8181', email='jo.blocgs@densitron.com', description='People Test Description', team_id=2, job_id=1).save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_people),
    ]
