# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160127_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='place_priority',
            field=models.SmallIntegerField(default=1, help_text='Display priority list. 1 - top, 2+ - bottom.'),
        ),
    ]
