# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20160128_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('get_emails', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField(editable=False)),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=64)),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to_email', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
