# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_admin_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='to_email',
            field=models.CharField(max_length=255),
        ),
    ]
