# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20160203_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('job', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ContactUser'),
        ),
    ]
