# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20160315_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Field for comments.')),
                ('title', models.CharField(max_length=128)),
                ('line_1', models.CharField(max_length=128)),
                ('line_2', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=36)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['job__place_priority', 'place_priority'], 'verbose_name_plural': 'People'},
        ),
    ]
