# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_pages', '0003_auto_20160415_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitiesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Field for comments.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='opportunities_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elastic_pages.OpportunitiesBlock'),
        ),
    ]
