# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_pages', '0004_auto_20160418_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageheaddropmenu',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='pageheaddropmenuelement',
            options={'ordering': ['priority']},
        ),
    ]
