# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_pages', '0005_auto_20160420_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobject',
            name='embed_video',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
