# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_pages', '0006_auto_20160420_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsgalleryblock',
            name='image_left',
            field=models.ImageField(help_text='The recommended width of a image is 475px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postsgalleryblock',
            name='image_middle',
            field=models.ImageField(help_text='The recommended width of a image is 475px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='postsgalleryblock',
            name='image_right',
            field=models.ImageField(help_text='The recommended width of a image is 475px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='slideelement',
            name='background',
            field=models.ImageField(help_text='The recommended size of image is 1440px/396px But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
        ),
    ]
