# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='LowPowerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='MonochromeProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='OledProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TftIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TftProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('colour', models.BooleanField(default=True)),
                ('resolution', models.CharField(max_length=12)),
                ('brightness', models.IntegerField(default=0)),
                ('viewing_angle', models.CharField(max_length=15)),
                ('features', models.ManyToManyField(to='products.Feature')),
                ('tft_i_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TftIF')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='TouchPanelProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('active_area_w', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active_area_h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('touch_points', models.SmallIntegerField(default=1)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Controller')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Interface')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Structure')),
                ('supported_os', models.ManyToManyField(to='products.Os')),
            ],
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='touch',
        ),
        migrations.AlterField(
            model_name='touch',
            name='i_f',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tftproduct',
            name='touch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Touch'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
            preserve_default=False,
        ),
    ]
