# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160107_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1234, help_text='The recommended size of a image is 80 x 80(+/-) px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(default=123, help_text='The recommended size of a image is 80 x 80(+/-) px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touch',
            name='i_f',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Touch I/F'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='points',
            field=models.SmallIntegerField(default=1, verbose_name='Touch Points'),
        ),
        migrations.AlterField(
            model_name='touch',
            name='type',
            field=models.CharField(max_length=128, verbose_name='Touch Type'),
        ),
    ]
