# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_load_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField(help_text='Add text as html code. For example')),
                ('image', models.ImageField(upload_to='images')),
                ('is_view_image_button', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='The recommended size of a image is 80 x 80(+/-) px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='The recommended size of a image is 80 x 80(+/-) px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images')),
                ('characteristic', models.ManyToManyField(to='products.Characteristic')),
                ('key_benefits', models.ManyToManyField(related_name='key_benefits', to='products.Bullet')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Service')),
                ('why_densitron', models.ManyToManyField(related_name='why_densitron', to='products.Bullet')),
            ],
        ),
    ]
