# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_doc_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='commonly_used',
            field=models.ManyToManyField(related_name='commonly_used', to='products.Bullet'),
        ),
        migrations.AddField(
            model_name='product',
            name='why_dens',
            field=models.ManyToManyField(related_name='why_dens', to='products.Bullet'),
        ),
        migrations.AddField(
            model_name='product',
            name='commonly_used_in',
            field=models.ManyToManyField(related_name='commonly_used_in', to='products.UsedIn'),
        ),
    ]
