# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160209_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('spec', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='commonly_used_in',
            field=models.ManyToManyField(blank=True, related_name='commonly_used_in', to='products.UsedIn'),
        ),
    ]
