# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160212_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftproduct',
            name='touch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Touch'),
        ),
    ]
