# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20160212_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tftproduct',
            name='tft_i_f',
        ),
        migrations.AddField(
            model_name='tftproduct',
            name='tft_i_f',
            field=models.ManyToManyField(to='products.TftIF'),
        ),
    ]
