# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_lowpowerproduct_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftproduct',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.Feature'),
        ),
    ]
