# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_lowpowerproduct_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='active_area_h',
        ),
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='active_area_w',
        ),
        migrations.AddField(
            model_name='product',
            name='active_area_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active_area_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
