# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20160215_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='monochromeproduct',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Controller'),
        ),
    ]
