# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_monochromeproduct_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_w',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=18),
        ),
    ]
