# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20160215_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowpowerproduct',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='lowpowerproduct',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='monochromeproduct',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='features',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='tft_i_f',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='touch',
        ),
        migrations.RemoveField(
            model_name='tftproduct',
            name='viewing_angle',
        ),
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='interface',
        ),
        migrations.AddField(
            model_name='product',
            name='brightness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Controller'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.Feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='interface',
            field=models.ManyToManyField(blank=True, to='products.Interface'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tft_interface',
            field=models.ManyToManyField(blank=True, to='products.TftIF'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Touch'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewing_angle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='viewing_area_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='viewing_area_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='touchpanelproduct',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Structure'),
        ),
        migrations.AlterField(
            model_name='touchpanelproduct',
            name='touch_points',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
