# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20160216_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='supported_os',
        ),
        migrations.RemoveField(
            model_name='touchpanelproduct',
            name='touch_points',
        ),
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Structure'),
        ),
        migrations.AddField(
            model_name='product',
            name='supported_os',
            field=models.ManyToManyField(blank=True, to='products.Os'),
        ),
        migrations.AddField(
            model_name='product',
            name='touch_points',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
