# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20160216_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.ManyToManyField(blank=True, to='products.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brightness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brightness (cd/m2)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Controller', verbose_name='Controller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.Feature', verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='interface',
            field=models.ManyToManyField(blank=True, to='products.Interface', verbose_name='Interface'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=18, verbose_name='Size (inches)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Structure', verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supported_os',
            field=models.ManyToManyField(blank=True, to='products.Os', verbose_name='Supported Os'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tft_interface',
            field=models.ManyToManyField(blank=True, to='products.TftIF', verbose_name='TFT Interface'),
        ),
        migrations.AlterField(
            model_name='product',
            name='touch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Touch', verbose_name='Touch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='touch_points',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Touch Points'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewing_angle',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Viewing Angle (U/D/L/R)'),
        ),
    ]
