# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20160217_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='touch_points',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Touch Points'),
        ),
    ]
