# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20160217_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Field for comments.', null=True)),
                ('title', models.CharField(max_length=128)),
                ('top_text', models.TextField(blank=True, null=True)),
                ('left_photo', models.ImageField(blank=True, help_text='The recommended size of a image is 278 x 209 px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', null=True, upload_to='images')),
                ('left_photo_caption', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_text', models.TextField(blank=True, null=True)),
                ('right_photo', models.ImageField(help_text='The recommended size of a image is 278 x 209 px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', upload_to='images')),
                ('right_photo_caption', models.CharField(blank=True, max_length=128, null=True)),
                ('bottom_text', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
