# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publicated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='right_photo',
            field=models.ImageField(blank=True, help_text='The recommended size of a image is 278 x 209 px. But you can use any image sizes, they will be compressed or increased to the appropriate value.', null=True, upload_to='images'),
        ),
    ]
