# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20160223_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resolution_h',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution_w',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
