# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20160223_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tftif',
            name='interface_type',
            field=models.CharField(choices=[('RGB', 'RGB'), ('LVDS', 'LVDS'), ('HDMI', 'HDMI'), ('USB', 'USB'), ('MIPI', 'MIPI'), ('DPPT', 'Display port'), ('MPU', 'MPU'), ('DVI', 'DVI'), ('SRL', 'Serial')], default='RGB', max_length=4),
        ),
    ]
