# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_tftif_interface_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('link', models.URLField(help_text='Link to the Twitter message')),
                ('publicated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
