# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_twitt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitt',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='twitt',
            old_name='name',
            new_name='title',
        ),
    ]
