# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20160224_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
