# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20160226_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='country_flag',
            field=models.ManyToManyField(blank=True, related_name='country_flag', to='products.CountryFlag'),
        ),
    ]
