# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20160309_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
