# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20160315_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Sub-Category', 'verbose_name_plural': 'Product Sub-categories'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Doc', 'verbose_name_plural': 'Docs'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'Sub-category service', 'verbose_name_plural': 'Sub-category services'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
