# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20160411_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Spec'),
        ),
    ]
