# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20160415_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', '-priority'], 'verbose_name': 'Product Sub-Category', 'verbose_name_plural': 'Product Sub-categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(default=1, help_text='Placing priority of the element among the same types, 1 - the first, 2 - of the second and so on.'),
        ),
    ]
