# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20160420_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
